version: '3.8'

services:
    mysql:
        image: mysql:8.0
        platform: linux/x86_64
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql-db:/var/lib/mysql
        networks:
            - mysql-network

volumes:
    mysql-db:
networks:
    mysql-network:
        driver: bridge
